### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by jul** [dailymotion/picomongo#3]
virtualenv with py2.7 

install command used: 

```
pip install git+https://github.com/dailymotion/picomongo
```

1- requirements seems to be missing pymongo.
2- And while trying to run tests:

```
$ python -munittest  discover
E..........
======================================================================
ERROR: test_document (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_document
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/home/jul/src/parseweblog/parseweblog/picomongo/tests/test_document.py", line 4, in    <module>
import pymongo.objectid
ImportError: No module named objectid


----------------------------------------------------------------------
Ran 11 tests in 0.040s

FAILED (errors=1)
```

**Comment by Lothiraldan** [comment]
Pymongo is listed as dependence in setup.py, which tools do you use to install picomongo (pip, python setup.py).
It seems that pymongo has moved objectif from pymongo modle to pymongo, which pymongo version do you use? Anyway it's just imported in test file, it should not be a problem.
Thanks for testing

**Comment by jul** [comment]
So it is a false positive then.

2.3 

```
$ python
Python 2.7.3 (default, Aug  1 2012, 05:14:39) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymongo as pm
>>> pm.version
'2.3'
```
